server.port=8088

spring.application.name=NotificationService

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_URI:http://localhost:9092}
spring.kafka.consumer.group-id=notificationGroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# Eureka Client
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

logging.file.name=/logs/zion.log
logging.level.root=INFO
#logging.level.org.springframework=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Send logs to Logstash
logging.logback.appender.logstash.destination=localhost:5044

